[toolchain]
channel = "nightly-2023-04-22" # or "nightly-YYYY-MM-DD" for a specific date
profile = "minimal"
components = [ "rust-src", "llvm-tools-preview" ]
targets = [ "thumbv7em-none-eabihf", "arm-unknown-linux-gnueabihf" ]
